# Generated by Django 5.1.6 on 2025-02-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acd_track', '0002_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='students',
            name='roll_number',
        ),
        migrations.AddField(
            model_name='students',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='reg_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
