# Generated by Django 5.1.6 on 2025-02-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acd_track', '0004_lecture_alter_students_mobile_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
    ]
